import type { TestDefinition, AgeCategory, TestCategory } from '../types/detection';

export const TEST_CATALOG: TestDefinition[] = [
  // --- SPEED ---
  {
    id: 'sprint_15m',
    name: 'Sprint 15m',
    shortName: '15m',
    category: 'speed',
    unit: 's',
    direction: 'lower_better',
    description: 'Sprint lineaire 15 metres depart arrete',
    precision: 2,
    minValue: 2.0,
    maxValue: 5.0,
    excludedCategories: ['U13', 'U15', 'U17', 'U18', 'U21', 'Senior'],
  },
  {
    id: 'sprint_20m',
    name: 'Sprint 20m',
    shortName: '20m',
    category: 'speed',
    unit: 's',
    direction: 'lower_better',
    description: 'Sprint lineaire 20 metres depart arrete',
    precision: 2,
    minValue: 2.5,
    maxValue: 5.0,
    excludedCategories: ['U11'],
  },
  {
    id: 'sprint_3qt',
    name: 'Sprint 3/4 terrain (21m)',
    shortName: '3/4',
    category: 'speed',
    unit: 's',
    direction: 'lower_better',
    description: 'Sprint 3/4 de terrain basket (21 metres)',
    precision: 2,
    minValue: 2.5,
    maxValue: 5.5,
    excludedCategories: ['U11'],
  },
  {
    id: 'suicide_17',
    name: 'Navette suicide 17m',
    shortName: 'Suicide',
    category: 'speed',
    unit: 's',
    direction: 'lower_better',
    description: 'Navette aller-retour 17m (ligne de fond a LF et retour x4)',
    precision: 2,
    minValue: 20.0,
    maxValue: 50.0,
  },
  // --- AGILITY ---
  {
    id: 't_test',
    name: 'T-Test',
    shortName: 'T-Test',
    category: 'agility',
    unit: 's',
    direction: 'lower_better',
    description: 'Parcours en T : avant, lateral gauche, lateral droit, recul',
    precision: 2,
    minValue: 8.0,
    maxValue: 18.0,
  },
  {
    id: 'lane_agility',
    name: 'Lane Agility Drill',
    shortName: 'Lane',
    category: 'agility',
    unit: 's',
    direction: 'lower_better',
    description: 'Parcours perimetre de la raquette en defense',
    precision: 2,
    minValue: 9.0,
    maxValue: 20.0,
  },
  {
    id: 'pro_agility',
    name: 'Pro Agility 5-10-5',
    shortName: '5-10-5',
    category: 'agility',
    unit: 's',
    direction: 'lower_better',
    description: '5 yards droite, 10 yards gauche, 5 yards droite',
    precision: 2,
    minValue: 3.5,
    maxValue: 8.0,
  },
  // --- POWER ---
  {
    id: 'vert_no_step',
    name: 'Detente verticale sans elan',
    shortName: 'Vert0',
    category: 'power',
    unit: 'cm',
    direction: 'higher_better',
    description: "Saut vertical pieds joints sans pas d'elan",
    precision: 0,
    minValue: 5,
    maxValue: 100,
  },
  {
    id: 'vert_max',
    name: 'Detente verticale avec elan',
    shortName: 'VertMax',
    category: 'power',
    unit: 'cm',
    direction: 'higher_better',
    description: "Saut vertical avec 1 ou 2 pas d'elan",
    precision: 0,
    minValue: 5,
    maxValue: 120,
  },
  {
    id: 'broad_jump',
    name: 'Saut longueur sans elan',
    shortName: 'Broad',
    category: 'power',
    unit: 'cm',
    direction: 'higher_better',
    description: 'Saut en longueur pieds joints depart arrete',
    precision: 0,
    minValue: 50,
    maxValue: 320,
  },
  // --- ENDURANCE ---
  {
    id: 'yoyo_ir1',
    name: 'Yo-Yo IR1',
    shortName: 'YoYo',
    category: 'endurance',
    unit: 'palier',
    direction: 'higher_better',
    description: 'Yo-Yo Intermittent Recovery Test niveau 1',
    precision: 1,
    minValue: 5.0,
    maxValue: 25.0,
    excludedCategories: ['U11', 'U13'],
  },
  {
    id: 'luc_leger',
    name: 'Luc Leger',
    shortName: 'Leger',
    category: 'endurance',
    unit: 'palier',
    direction: 'higher_better',
    description: 'Test navette 20m multi-paliers (bip test)',
    precision: 1,
    minValue: 2.0,
    maxValue: 16.0,
  },
  // --- SKILLS (mapped to agility axis in engine) ---
  {
    id: 'dribble_course',
    name: 'Parcours dribble',
    shortName: 'Dribble',
    category: 'agility',
    unit: 's',
    direction: 'lower_better',
    description: 'Parcours de dribble chronometre avec changements de direction',
    precision: 2,
    minValue: 8.0,
    maxValue: 30.0,
  },
  {
    id: 'def_slides',
    name: 'Slides defensifs',
    shortName: 'Slides',
    category: 'agility',
    unit: 's',
    direction: 'lower_better',
    description: 'Deplacements lateraux defensifs chronometres',
    precision: 2,
    minValue: 5.0,
    maxValue: 18.0,
  },
  // --- SHOOTING ---
  {
    id: 'ft_10',
    name: 'Lancers francs (x/10)',
    shortName: 'LF',
    category: 'shooting',
    unit: '/10',
    direction: 'higher_better',
    description: '10 lancers francs consecutifs',
    precision: 0,
    minValue: 0,
    maxValue: 10,
  },
  {
    id: 'midrange_10',
    name: 'Tir mi-distance 5 spots (x/10)',
    shortName: 'Mid',
    category: 'shooting',
    unit: '/10',
    direction: 'higher_better',
    description: '2 tirs par spot sur 5 positions mi-distance',
    precision: 0,
    minValue: 0,
    maxValue: 10,
  },
  {
    id: 'three_pt_10',
    name: 'Tir 3 points 5 spots (x/10)',
    shortName: '3PT',
    category: 'shooting',
    unit: '/10',
    direction: 'higher_better',
    description: '2 tirs par spot sur 5 positions 3 points',
    precision: 0,
    minValue: 0,
    maxValue: 10,
    excludedCategories: ['U11'],
  },
  {
    id: 'catch_shoot',
    name: 'Catch & shoot chrono (x/10)',
    shortName: 'C&S',
    category: 'shooting',
    unit: '/10',
    direction: 'higher_better',
    description: '10 tirs en reception, chronometre',
    precision: 0,
    minValue: 0,
    maxValue: 10,
    excludedCategories: ['U11', 'U13'],
  },
  // --- ANTHROPOMETRY ---
  {
    id: 'height_barefoot',
    name: 'Taille pieds nus',
    shortName: 'Taille',
    category: 'anthropometry',
    unit: 'cm',
    direction: 'higher_better',
    description: 'Taille mesuree pieds nus',
    precision: 1,
    minValue: 100,
    maxValue: 230,
  },
  {
    id: 'height_shoes',
    name: 'Taille chaussures',
    shortName: 'T+Chau',
    category: 'anthropometry',
    unit: 'cm',
    direction: 'higher_better',
    description: 'Taille mesuree en chaussures de basket',
    precision: 1,
    minValue: 102,
    maxValue: 235,
  },
  {
    id: 'wingspan',
    name: 'Envergure',
    shortName: 'Enverg',
    category: 'anthropometry',
    unit: 'cm',
    direction: 'higher_better',
    description: 'Distance doigt a doigt bras tendus',
    precision: 1,
    minValue: 100,
    maxValue: 250,
    excludedCategories: ['U11'],
  },
  {
    id: 'standing_reach',
    name: 'Standing reach',
    shortName: 'Reach',
    category: 'anthropometry',
    unit: 'cm',
    direction: 'higher_better',
    description: 'Portee bras leve pieds a plat',
    precision: 1,
    minValue: 130,
    maxValue: 310,
    excludedCategories: ['U11', 'U13'],
  },
  {
    id: 'weight',
    name: 'Poids',
    shortName: 'Poids',
    category: 'anthropometry',
    unit: 'kg',
    direction: 'higher_better',
    description: 'Poids du joueur',
    precision: 1,
    minValue: 25,
    maxValue: 150,
    excludedCategories: ['U11'],
  },
];

export function getTestById(testId: string): TestDefinition | undefined {
  return TEST_CATALOG.find((t) => t.id === testId);
}

export function getEligibleTests(category: AgeCategory): TestDefinition[] {
  return TEST_CATALOG.filter(
    (t) => !t.excludedCategories || !t.excludedCategories.includes(category)
  );
}

export function getEligibleTestsByCategory(
  category: AgeCategory,
  testCategory: TestCategory
): TestDefinition[] {
  return getEligibleTests(category).filter((t) => t.category === testCategory);
}

export function isTestEligible(testId: string, category: AgeCategory): boolean {
  const test = getTestById(testId);
  if (!test) return false;
  return !test.excludedCategories || !test.excludedCategories.includes(category);
}
